operations:
  - operation: sepia
  - operation: brightness
    opts: 0.3
  - operation: crop
    opts: 500 500
  - operation: resize
    opts: 400 400
  - operation: exaudio
  #- operation: grayscale
  #  opts: 0.3
  #- operation: format
  #  opts: mov
