operations:
  - operation: sepia
  - operation: brightness
    opts: 0.3
  - operation: grayscale
    opts: 0.3
  - operation: crop
    opts: 500 500
  - operation: format
    opts: mov
  - operation: resize
    opts: 400 400
  - operation: exaudio